services:
  database:
    image: mongo:5.0
    container_name: "database"
    ports:
      - 27017:27017
    command:
  api:
    build:
      context: spring-boot-student-app-api
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - MONGO_URL=mongodb://database:27017/dev
    ports:
      - "8080:8080"
  web:
    build:
      context: react-student-management
      dockerfile: Dockerfile
    environment:
      - REACT_APP_API_URL=http://47.129.106.221:8080
    ports:
      - "3000:3000"
    networks:
      - webnet
networks:
  webnet:
    driver: bridge
